Parker dev
flywheel-apps/fsl-topup pull request #2
Opened 2020-01-08 16:07 UTC by dpark6060

2020-01-08 22:27 UTC, NPann requested changes
Quite a lot to review here
Maybe worth having a run example on ss.ce before merging.

2020-01-08 22:27 UTC, NPann commented on README.md
> +*Presently only runs on files that have been corrected with topup.  Won't work if **topup_only** is true*
Formatting does not render new line here. double space missing after **image_2** I believe

2020-01-08 22:27 UTC, NPann commented on README.md
> +© Copyright 2019, Josh Revision
Pun intended? (re the Josh Revision)

2020-01-08 22:27 UTC, NPann commented on run.py
> +    log = logging.getLogger('root')
The logger get redefined in each sub function later. remove?

2020-01-09 18:22 UTC, dpark6060 commented on README.md
> +*Presently only runs on files that have been corrected with topup.  Won't work if **topup_only** is true*
https://ss.ce.flywheel.io/#/jobslog/job/5dfbb690f999360023e1bf21

2020-01-09 18:26 UTC, dpark6060 commented on README.md
> +*Presently only runs on files that have been corrected with topup.  Won't work if **topup_only** is true*
ugh yeah pycharm keeps removing trailing spaces :(

2020-01-09 21:16 UTC, NPann approved these changes

2020-01-09 21:18 UTC, NPann commented on README.md
> +*Presently only runs on files that have been corrected with topup.  Won't work if **topup_only** is true*
weird

2020-01-09 23:16 UTC, joshicola commented on README.md
> +© Copyright 2019, Josh Revision
Bwahahhhaaa!

2020-01-09 23:23 UTC, joshicola approved these changes

2020-01-09 23:23 UTC, joshicola commented on common.py
> +def exec_command(command, shell=False, stdout_msg=None, cont_output=False):
This form is now in the gear-toolkit.
I don't know if you need the 'environ' for this.

2020-01-09 23:23 UTC, joshicola commented on common.py
> +log = logging.getLogger()
I suppose we will talk more about how we do logging.

I am in favor of identifying the module and function we are logging from....

I guess more to come.

2020-01-10 00:14 UTC, merged